import type { Metadata } from "next";
import { Grand_Hotel } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
const Hotel = Grand_Hotel({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-background", Hotel.className)}>{children}</body>
    </html>
  );
}
